In [56]:
# import pandas lib as pd
import pandas as pd
import re
import pandas as pd

# read by default 1st sheet of an excel file
# dataframe1 = pd.read_excel('E://REVA//Healthcare Providers Data For Anomaly Detection//Medicare1//2021_CA_Data.xlsx',sheet_name="Sheet1",header=0)
dataframe1 = pd.read_excel('E://GitHub//healthcare_provider_recommendation//2021_CA_Data.xlsx',sheet_name="data1",header=0)

df1 = dataframe1[dataframe1['Rndrng_Prvdr_Zip5'] == 90095] #user input
df2=df1[df1["HCPCS_Desc"].str.contains("patient")]
df2 = df2[df2['HCPCS_Cd'] == 99205] #user input
df2 = df2[df2['Rndrng_Prvdr_Type'] == 'Neurology'] #user input

In [57]:
df3=df2

In [58]:
# Find the maximum rank value in the 'Tot_Bene_Day_Srvcs_rank_natop2' column
max_rank_value = df3['Avg_Sbmtd_Chrg'].max()

# Create a new column with values in reverse order
df3['Reverse_Avg_Sbmtd_Chrg'] = max_rank_value - df3['Avg_Sbmtd_Chrg'] + 1

# Create a new column 'Sum_Columns' by adding 'Column1' and 'Column2'
df3['sum_beneficiary_days_and_rev_avg_charge'] = df3['Tot_Bene_Day_Srvcs'] + df3['Reverse_Avg_Sbmtd_Chrg']

# # Calculate the percentiles (as quantiles between 0 and 1)
# percentiles = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.01]

# # Use the 'qcut' function to bin the data based on percentiles
# df3['Bucket'] = pd.qcut(df3['sum_beneficiary_days_and_rev_avg_charge'], q=quantiles, labels=False, precision=0)
# Check the unique values in the 'Bucket' column

# # Define the number of bins (in this case, 10)
# num_bins = 10

# # Use the 'cut' function to create bins and assign each value to a bin
# df3['Bucket_Normalized'] = pd.cut(df3['sum_beneficiary_days_and_rev_avg_charge'], bins=num_bins, labels=False)

# df3.to_excel('E://REVA//Healthcare Providers Data For Anomaly Detection//Medicare1//df3_16_output.xlsx', index=False, engine='openpyxl')

In [59]:
from sklearn.preprocessing import LabelEncoder

# Find the maximum value in the column
max_value = df3['sum_beneficiary_days_and_rev_avg_charge'].max()

# Use the apply function to create a new column with 1 for the max value and 0 for others
df3['Binary_sum_beneficiary_days_and_rev_avg_charge'] = df3['sum_beneficiary_days_and_rev_avg_charge'].apply(lambda x: 1 if x == max_value else 0)

# Assuming you have already loaded and preprocessed your data
selected_columns=[ 'Rndrng_Prvdr_Last_Org_Name','Rndrng_Prvdr_First_Name','Rndrng_Prvdr_MI', 'Rndrng_Prvdr_Crdntls', 'Rndrng_Prvdr_Gndr',
       'Rndrng_Prvdr_Ent_Cd', 'Rndrng_Prvdr_St1', 'Rndrng_Prvdr_St2',
       'Rndrng_Prvdr_City', 'Rndrng_Prvdr_State_Abrvtn',
       'Rndrng_Prvdr_State_FIPS', 'Rndrng_Prvdr_Zip5', 'Rndrng_Prvdr_RUCA',
       'Rndrng_Prvdr_RUCA_Desc', 'Rndrng_Prvdr_Cntry', 'Rndrng_Prvdr_Type',
       'Rndrng_Prvdr_Mdcr_Prtcptg_Ind', 'HCPCS_Cd', 'HCPCS_Desc',
       'HCPCS_Drug_Ind', 'Place_Of_Srvc', 'Tot_Benes', 'Tot_Srvcs',
       'Tot_Bene_Day_Srvcs', 'Avg_Sbmtd_Chrg', 'Avg_Mdcr_Alowd_Amt',
       'Avg_Mdcr_Pymt_Amt', 'Avg_Mdcr_Stdzd_Amt']

# List of columns to label encode
columns_to_encode = selected_columns

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

df4=df3

# # Encode the selected columns
# for column in columns_to_encode:
#     df4[column] = label_encoder.fit_transform(df4[column])
df4.to_excel('E://REVA//Healthcare Providers Data For Anomaly Detection//Medicare1//df4_32_output.xlsx', index=False, engine='openpyxl')

In [60]:
selected_columns_text=[ 'Rndrng_Prvdr_Last_Org_Name','Rndrng_Prvdr_First_Name','Rndrng_Prvdr_MI', 'Rndrng_Prvdr_Crdntls', 'Rndrng_Prvdr_Gndr',
       'Rndrng_Prvdr_Ent_Cd'
                       , 'Rndrng_Prvdr_St1'
                       , 'Rndrng_Prvdr_St2',
       'Rndrng_Prvdr_City', 'Rndrng_Prvdr_State_Abrvtn',        
       'Rndrng_Prvdr_RUCA_Desc', 'Rndrng_Prvdr_Cntry', 'Rndrng_Prvdr_Type',
       'Rndrng_Prvdr_Mdcr_Prtcptg_Ind', 'HCPCS_Desc',
       'HCPCS_Drug_Ind', 'Place_Of_Srvc','HCPCS_category','HCPCS_sub category']

selected_columns_numeric=[ 
       'Rndrng_Prvdr_State_FIPS', 'Rndrng_Prvdr_Zip5', 'Rndrng_Prvdr_RUCA','Tot_Benes', 'Tot_Srvcs',
       'Tot_Bene_Day_Srvcs', 'Avg_Sbmtd_Chrg', 'Avg_Mdcr_Alowd_Amt',
       'Avg_Mdcr_Pymt_Amt', 'Avg_Mdcr_Stdzd_Amt']

mixed_column='HCPCS_Cd'

for column in df4.columns:
    if column in selected_columns_text:
        df4[column].fillna('na', inplace=True) 
        label_encoder = LabelEncoder()
        df4[column] = label_encoder.fit_transform(df4[column])   
    # if column in selected_columns_text:
        
        
    #     print(column, df4[column].dtype)
    #     unique_values = df4[column].nunique()
    #     data_type = df4[column].dtype
    # # Fill NaN values with 'na'
        
    #     label_encoder = LabelEncoder()
    #     df4[column] = label_encoder.fit_transform(df4[column])    
    #     if unique_values == 1:            
    #         print(column, df4[column].dtype)
    #         df4=df4.drop(column, axis=1, inplace=True)
df4.to_excel('E://REVA//Healthcare Providers Data For Anomaly Detection//Medicare1//df4_29_output.xlsx', index=False, engine='openpyxl')

In [61]:

# Iterate through columns
for column in df4.columns:
    if column in selected_columns_numeric:
        print(column, df4[column].dtype)
        # # Convert the column to numeric if possible, ignoring errors
        # df4[column] = pd.to_numeric(df4[column], errors='coerce')
        
        # Find the least non-null value in the column
        least_value = df4[column].min(skipna=True)
        
        unique_values = df4[column].nunique()
        data_type = df4[column].dtype
    
        # Fill null values with the least value
        df4[column].fillna(least_value, inplace=True)
df4.to_excel('E://REVA//Healthcare Providers Data For Anomaly Detection//Medicare1//df4_33_output.xlsx', index=False, engine='openpyxl')

Rndrng_Prvdr_State_FIPS int64
Rndrng_Prvdr_Zip5 int64
Rndrng_Prvdr_RUCA int64
Tot_Benes int64
Tot_Srvcs float64
Tot_Bene_Day_Srvcs int64
Avg_Sbmtd_Chrg float64
Avg_Mdcr_Alowd_Amt float64
Avg_Mdcr_Pymt_Amt float64
Avg_Mdcr_Stdzd_Amt float64

In [62]:
df4.head()

,Rndrng_NPI,Rndrng_Prvdr_Last_Org_Name,Rndrng_Prvdr_First_Name,Rndrng_Prvdr_MI,Rndrng_Prvdr_Crdntls,Rndrng_Prvdr_Gndr,Rndrng_Prvdr_Ent_Cd,Rndrng_Prvdr_St1,Rndrng_Prvdr_St2,Rndrng_Prvdr_City,...,Avg_Mdcr_Alowd_Amt,Avg_Mdcr_Pymt_Amt,Avg_Mdcr_Stdzd_Amt,LAT,LNG,HCPCS_category,HCPCS_sub category,Reverse_Avg_Sbmtd_Chrg,sum_beneficiary_days_and_rev_avg_charge,Binary_sum_beneficiary_days_and_rev_avg_charge
20576,1073908414,28,6,10,2,0,0,11,3,2,...,243.59,173.76,155.21,34.0712,-118.443523,0,0,6641.0,6659.0,0
20578,1104960517,6,4,4,2,1,0,12,3,2,...,200.51,150.42,136.86,34.0712,-118.443523,0,0,7536.0,7579.0,0
20580,1114940731,2,10,6,2,1,0,1,0,2,...,245.44,196.72,175.90,34.0712,-118.443523,0,0,6641.0,6657.0,0
20581,1114945474,20,26,5,2,0,0,1,0,2,...,245.34,186.47,166.96,34.0712,-118.443523,0,0,6641.0,6657.0,0
20591,1154356053,4,27,1,2,1,0,5,3,2,...,200.51,126.48,115.00,34.0712,-118.443523,0,0,6641.0,6655.0,0

In [63]:

# # Iterate through columns
for column in df4.columns:   
    unique_values = df4[column].nunique()
    data_type = df4[column].dtype
    # Drop the column if there's only one unique value
    if unique_values == 1:
        print(column, df4[column].dtype)
        df4=df4.drop(column, axis=1, inplace=True)
    
#     # Apply label encoding if there are multiple unique values and the data type is object (string)
#     if unique_values > 1 and data_type == 'object':
#         label_encoder = LabelEncoder()
#         df4[column] = label_encoder.fit_transform(df4[column])

Rndrng_Prvdr_Ent_Cd int32

TypeError: 'NoneType' object is not subscriptable